name: .NET Core

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
        source-url: https://nuget.pkg.github.com/krdmllr/KONMUE.Templates/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Pack
      run: dotnet pack templates/Xamarin/KONMUE.Templates.Xamarin.csproj --configuration Release
    - name: Publish
      run: dotnet nuget push "templates/Xamarin/bin/Release/*.nupkg" --source "github"
